---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  labels:
    type: webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      type: webserver
  template:
    metadata:
      name: apache-pod
      labels:
        type: webserver
    spec:
      containers:
        - name: apache
          image: httpd
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "200m"
              memory: "150Mi"
...
