piVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql
spec:
  clusterIP: None
  selector:
    app: mysql
  ports:
    - name: tcp
      protocol: TCP
      port: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql-service
  template:
    metadata:
      name: mysql-pod
      labels:
        app: mysql
    spec:
      containers:
        - name: mydb
          image: mysql:5
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: ram
          volumeMounts:
            - name: my-pv-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: my-pv-storage
          persistentVolumeClaim:
            claimName: my-pvc
...
