---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-deployment
  labels:
    type: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      type: blue
  template:
    metadata:
      name: nginx-pod
      labels:
        type: blue
    spec:
      containers:
        - name: nginx
          image: nginx:1.23
---
apiVersion: v1
kind: Service
metadata:
  name: blue-service
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      nodePort: 30009
      port: 80
  selector:
    type: blue
...
