---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-deployment1
  labels:
    type: green
spec:
  replicas: 2
  selector:
    matchLabels:
      type: green
  template:
    metadata:
      name: nginx-pod
      labels:
        type: green
    spec:
      containers:
        - name: nginx
          image: nginx:1.24
---
apiVersion: v1
kind: Service
metadata:
  name: green-service
spec:
  type: LoadBalancer
  selector:
    type: green
  ports:
    - targetPort: 80
      nodePort: 30008
      port: 80
...
