apiVersion: v1
kind: Service
metadata: 
  name: nginx-service
  labels:
    author: ram

spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      nodePort: 30008
      port: 8080
  selector:
    type: proxy
