---
apiVersion: v1
kind: ReplicationController
metadata: 
  name: httpd-rc
  labels:
    author: ram
    type: webserver
spec:
  replicas: 1
  template:
    metadata: 
      name: httpd-pod
      labels:
        author: ram
        type: webserver
    spec:
      containers: 
        - name: myhttpd
          image: httpd
          ports:
            - containerPort: 80
              hostPort: 8080       

