---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  labels:
    author: ram
spec:
  type: LoadBalancer
  ports:
    - targetPort: 8080
      port: 8081
  selector:
    author: ram 
    type: ci-cd
...
