---
apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
  labels: 
    author: ram
    name: appserver
spec: 
  containers:
    - name: apache
      image: httpd
      ports:
        - containerPort: 80
          hostPort: 9090

...
