---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    type: db
spec:
  replicas: 2
  selector:
    matchLabels:
      type: db
  template:
    metadata:
      name: mysql-pod
      labels:
        type: db
    spec:
      containers:
        - name: mysql
          image: mysql:5
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: ram
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    author: ram
spec:
  ports:
    - targetPort: 3306
      port: 3306
  selector:
    type: db
