---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    type: db
spec:
  containers:
    - name: mysql
      image: mysql:5
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: a
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels: 
    author: ram
type: Opaque
stringData:
  a: ram
...

