---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: tomcat-deployment
  labels:
    author: ram
    type: webserver
spec:
  replicas: 3
  selector:
    matchLabels:
      type: webserver
  template:
    metadata:
      name: tomcat-pod
      labels:
        type: webserver
    spec:
      containers:
        - name: tomcat
          image: tomee
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: slave1
                    operator: In
                    values:
                      - ram

---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  labels:
    author: ram
spec:
  type: NodePort
  ports:
    - targetPort: 8080
      nodePort: 30450
      port: 8080
  selector:
    type: webserver
...
