---
apiVersion: v1
kind: Pod
metadata:
  name: apache-pod
  labels:
    author: ram
    type: appserver
spec:
  containers:
    - name: apache
      image: httpd
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: slave1
                operator: In
                values:
                  - ram
---
apiVersion: v1
kind: Service
metadata:
  name: apache-service
  labels:
    author: ram
spec:
  type: NodePort
  ports:
    - targetPort: 80
      nodePort: 30008
      port: 8080
  selector:
    author: ram
    type: appserver
...
