---
apiVersion: v1
kind: Pod
metadata:
  name: apache-pod
  labels:
    author: ram 
    type: webserver
spec:
  containers:
    - name: apache
      image: httpd
      ports: 
        - containarPort: 80
          hostPort: 8080
      volumeMounts:
        - name: pvc-starage
          mountPath: /usr/local/apache2
  volumes:
    - name: pvc-storage
      persistentVolumeClaim:
        claimName: pvc
...
apiVersion: v1
kind: Pod
metadata:
  name: apache-pod
  labels:
    author: ram
    type: webserver
spec:
  containers:
    - name: apache
      image: httpd
      volumeMounts:
        - name: pvc-storage
          mountPath: /usr/local/apache2
  volumes:
    - name: pvc-storage
      persistentVolumeClaim:
        claimName: pvc
...
