---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    type: database
spec:
  replicas: 2
  selector:
    matchLabels:
      type: database
  template:
    metadata: 
      name: postgres-pod
      labels:
        type: database
    spec:
      containers: 
        - name: postgres
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: ram
            - name: POSTGRES_USER
              value: myuser
            - name: POSTGRES_DB
              value: mydb
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    author: ram
spec:
  ports:
    - targetPort: 5432
      port: 5432
  selector:
    type: database
...
