---
apiVersion: v1
kind: Secret
metadata: 
   name: postgres-secret
type: Opaque
stringData:
  username: myuser
  password: ram
  dbname: mydb

---
apiVersion: apps/v1
kind: Deployment
medatada:
  name: postgres-deployment
  labels:
    type: database
spec:
  replicas: 2
  selector:
    matchLabels:
      type: database
  template:
    metadata:
      name: postgres-pod
      labels:
        type: database
    spec:
      containers:
        - name: postgres
          image: postgres
          env:
            - name: PODTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: dbname
...
