---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemonset
  labels:
    author: ram
spec:
  selector:
    matchLabels:
      author: ram
  template:
    metadata:
      name: nginx-pod
      labels:
        author: ram
    spec:
      containers:
        - name: mynginx
          image: nginx
          ports:
            - containerPort: 80
              hostPort: 8080
...
