---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    type: proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      type: proxy
  template:
    metadata:
      name: nginx-pod
      labels:
        type: proxy
    spec:
      containers:
        - name: mynginx
          image: nginx
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                 - key: slave1
                   operator: In
                   values:
                     - ram
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    type: proxy

spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      nodePort: 30008
      port: 8080
  selector:
    type: proxy
...    
