---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    type: proxy
spec:
  containers:
    - name: mynginx
      image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: slave1
                operator: In
                values:
                  - ram
        
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    author: ram
spec:
  type: NodePort
  ports:
    - targetPort: 80
      nodePort: 30008
      port: 8080
  selector:
    type: proxy

...
